### PR TITLE
Less notification verbosity/redundancy

### PR DESCRIPTION
**Pull request by apmole**
* Only show "how to deativate" notification on first notification.
* Shorten text of "how to deativate" notification
* Do not show deactivation notification.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Awesome tnx, you gonna do any more commits to this plugin or should I publish with this change?

**Comment by JohnMcLear** [comment]
Also can you update the screen shot please?  While you have tjhings open ? 👯‍♀️

**Comment by apmole** [comment]
> Awesome tnx, you gonna do any more commits to this plugin or should I publish with this change?

Thank you. I need to make one more change. Actually, I do not completely understand this part of the code:

```javascript
  newMsgInner: function(authorName, author, text, sticky, timestamp, timestr) {
    if (window.webkitNotifications) {
      window.webkitNotifications.createNotification("", authorName, text).show();
    } else if (window.Notification) {
      // I shouldn't show them from me..
      if(author === clientVars.userId) return; // dont show my own!
      new Notification(authorName, { icon: null, body: text });
    }
  }
```

Why is `clientVars.userId` only checked on `window.Notification`, not `window.webkitNotifications`?

**Comment by JohnMcLear** [comment]
That's a bug from looking at it!

**Pull request merged**
